name: Deploy Java App to EC2 (No Docker, No ECR)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Upload artifact to S3
      env:
        AWS_REGION: us-east-1
        S3_BUCKET: code-bucket567
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region $AWS_REGION

        JAR_FILE=$(find build/libs -name "*.jar" | head -n 1)
        aws s3 cp "$JAR_FILE" s3://$S3_BUCKET/app.jar

    - name: Deploy on EC2 via SSH
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > ec2_key.pem
        chmod 400 ec2_key.pem

        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          aws s3 cp s3://code-bucket567/app.jar /home/ec2-user/app.jar
          nohup java -jar /home/ec2-user/app.jar > app.log 2>&1 &
        EOF
